[project]
name = "main-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LAPKA21", email = "mr.raccon321@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi==0.141.1",
    "gradio==6.28.0",
    "ipython==9.17.1",
    "jupyter==1.1.1",
    "numpy>=2.5.3",
    "pandas==3.0.6",
    "plotly==7.1.0",
    "scikit-learn==1.9.1",
    "seaborn==0.13.2",
    "uvicorn[standard]==0.54.0",
]

[project.scripts]
main-example = "main_example:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
